// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUb9qCgE0vdY7rqykD0T1O-I9x817TAhk',
    appId: '1:276571176774:web:725f1bbe89a6eb7097af47',
    messagingSenderId: '276571176774',
    projectId: 'vidar-9e8ac',
    authDomain: 'vidar-9e8ac.firebaseapp.com',
    databaseURL: 'https://vidar-9e8ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vidar-9e8ac.appspot.com',
    measurementId: 'G-JXT36B3WBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvw7itTY4p0mLqFArl_exmZmpzgafa2w',
    appId: '1:276571176774:android:931026e1f3660c7e97af47',
    messagingSenderId: '276571176774',
    projectId: 'vidar-9e8ac',
    databaseURL: 'https://vidar-9e8ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vidar-9e8ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyicdJt6YghaRJ_nM7pAShzmNoqPw_MUs',
    appId: '1:276571176774:ios:1546e7fbe261f22b97af47',
    messagingSenderId: '276571176774',
    projectId: 'vidar-9e8ac',
    databaseURL: 'https://vidar-9e8ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vidar-9e8ac.appspot.com',
    iosClientId: '276571176774-1kv4nit0gkflo62rsv7bt3lltvj7edjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.appComp',
  );
}
